### ISSUE TITLE
[bug] fswatcher error when starting z2m

### ISSUE THREAD

**Issue by chilicheech** [OpenZWave/Zwave2Mqtt#678]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt Docker version: 4.0.1

**Describe the bug**
When starting the container I get the following error:
```
z2m     | /usr/src/app/lib/Gateway.js:51
z2m     |         fn()
z2m     |         ^
z2m     |
z2m     | TypeError: fn is not a function
z2m     |     at FSWatcher.<anonymous> (/usr/src/app/lib/Gateway.js:51:9)
z2m     |     at FSWatcher.emit (events.js:315:20)
z2m     |     at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:135:12)
```

**To Reproduce**
1. Run the 4.0.1 image with no `customDevices` file
2. Observe the container fail with the error

**Expected behavior**
The container starts with no error

**Additional context**
This may be related to changes introduced by #670 and #675 

Downgrading to 4.0.0 makes it work again.

Cheers,

**Comment by niemyjski** [comment]
I'm still seeing this error even when building against master.

```
 z2m:App Listening on port 44920
/opt/lib/Gateway.js:51
        fn()
        ^

TypeError: fn is not a function
    at FSWatcher.<anonymous> (/opt/lib/Gateway.js:51:9)
    at FSWatcher.emit (events.js:315:20)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:135:12)
```

**Comment by jghaanstra** [comment]
For me 4.0.2 fixed this issue. Pulled from docker hub.

**Comment by pdbogen** [comment]
Would you mind confirming which SHA you're building? `git rev-parse HEAD`

Farther down in `lib/Gateway.js`, there are calls to `watch`, at lines 106, 107. What do these look like in your copy?

**Comment by pdbogen** [comment]
Yep, I think so as well; either docker cache, or maybe forgot to `git pull`, or other git wackiness. I wanted to confirm & make sure it's not something else, though.

**Comment by niemyjski** [comment]
I delete and rebuild the image locally. I'll ensure it's not being cached thanks!
